
name: Flutter build Mac

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
 build:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'beta'
         architecture: x64
     - run: flutter config --enable-macos-desktop
     - run: flutter build macos
